import type{PublishMediaItem}from"@kairo/domain/publishing";import type{PublishingAdapter,PublishingJob,ProviderPublishResult}from"./publishing";
type FetchLike=(input:string|URL|Request,init?:RequestInit)=>Promise<Response>;
export interface PublishingSecretResolver{resolve(credentialRef:string):Promise<string>}
export interface InstagramProcessingPolicy{maxChecks:number;intervalMs:number;sleep(ms:number):Promise<void>}
const defaultProcessing:InstagramProcessingPolicy={maxChecks:10,intervalMs:2000,sleep:(ms)=>new Promise(resolve=>setTimeout(resolve,ms))};
export class LinkedInOrganizationAdapter implements PublishingAdapter{readonly channel="linkedin" as const;constructor(private secrets:PublishingSecretResolver,private apiVersion:string,private fetchImpl:FetchLike=fetch){}supports(j:PublishingJob){return j.contentType==="text"&&j.content.length<=3000&&/^urn:li:organization:\d+$/.test(j.accountRef)}async publish(j:PublishingJob):Promise<ProviderPublishResult>{const token=await credential(this.secrets,j.credentialRef);if(!token)return{status:"failed",failureCode:"credential-unavailable",retryable:false};try{const r=await this.fetchImpl("https://api.linkedin.com/rest/posts",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json","linkedin-version":requiredVersion(this.apiVersion),"x-restli-protocol-version":"2.0.0"},body:JSON.stringify({author:j.accountRef,commentary:j.content,visibility:"PUBLIC",distribution:{feedDistribution:"MAIN_FEED",targetEntities:[],thirdPartyDistributionChannels:[]},lifecycleState:"PUBLISHED",isReshareDisabledByAuthor:false})});if(r.status===201){const id=r.headers.get("x-restli-id");return id?{status:"published",externalPostId:id}:{status:"unknown"}}return failure(r)}catch{return{status:"unknown"}}}}
export class InstagramProfessionalAdapter implements PublishingAdapter{readonly channel="instagram" as const;private processing:InstagramProcessingPolicy;constructor(private secrets:PublishingSecretResolver,private graphVersion:string,private fetchImpl:FetchLike=fetch,processing?:Partial<InstagramProcessingPolicy>){this.processing={...defaultProcessing,...processing,sleep:processing?.sleep??defaultProcessing.sleep}}supports(j:PublishingJob){if(j.content.length>2200||!/^\d+$/.test(j.accountRef))return false;const items=media(j);if(j.contentType==="image")return items.length===1&&items[0]?.kind==="image"&&safeMedia(items[0].url);if(j.contentType==="reel")return items.length===1&&items[0]?.kind==="video"&&safeMedia(items[0].url);if(j.contentType==="carousel")return items.length>=2&&items.length<=10&&items.every(item=>item.kind==="image"&&safeMedia(item.url));return false}async publish(j:PublishingJob):Promise<ProviderPublishResult>{const token=await credential(this.secrets,j.credentialRef);if(!token)return{status:"failed",failureCode:"credential-unavailable",retryable:false};const base=`https://graph.facebook.com/${requiredGraph(this.graphVersion)}`;try{if(j.contentType==="image")return this.publishImage(base,token,j);if(j.contentType==="reel")return this.publishReel(base,token,j);if(j.contentType==="carousel")return this.publishCarousel(base,token,j);return{status:"manual-required",reason:`instagram ${j.contentType} publishing is unavailable`}}catch{return{status:"unknown"}}}
private async publishImage(base:string,token:string,j:PublishingJob):Promise<ProviderPublishResult>{let container:string|undefined;try{const item=media(j)[0];const create=await this.post(base,token,j.accountRef,"media",{image_url:item?.url,caption:j.content});if(!create.ok)return failure(create);container=(await create.json()as{id?:string}).id;if(!container)return{status:"unknown"};return this.publishContainer(base,token,j.accountRef,container)}catch{return{status:"unknown",...(container?{providerCorrelationId:container}:{})}}}
private async publishReel(base:string,token:string,j:PublishingJob):Promise<ProviderPublishResult>{let container:string|undefined;try{const item=media(j)[0];const create=await this.post(base,token,j.accountRef,"media",{media_type:"REELS",video_url:item?.url,caption:j.content,share_to_feed:j.options?.instagram?.shareToFeed??false});if(!create.ok)return failure(create);container=(await create.json()as{id?:string}).id;if(!container)return{status:"unknown"};for(let check=0;check<this.processing.maxChecks;check++){const status=await this.fetchImpl(`${base}/${container}?fields=${encodeURIComponent("status_code,status")}`,{headers:{authorization:`Bearer ${token}`}});if(!status.ok)return failure(status,container);const data=await status.json()as{status_code?:string};if(data.status_code==="FINISHED")return this.publishContainer(base,token,j.accountRef,container);if(data.status_code==="ERROR")return{status:"failed",failureCode:"provider-media-processing-error",retryable:false,providerCorrelationId:container};if(check<this.processing.maxChecks-1)await this.processing.sleep(this.processing.intervalMs)}return{status:"failed",failureCode:"provider-media-processing-pending",retryable:true,providerCorrelationId:container}}catch{return{status:"unknown",...(container?{providerCorrelationId:container}:{})}}}
private async publishCarousel(base:string,token:string,j:PublishingJob):Promise<ProviderPublishResult>{let parent:string|undefined;try{const children:string[]=[];for(const item of media(j)){const create=await this.post(base,token,j.accountRef,"media",{image_url:item.url,is_carousel_item:true});if(!create.ok)return failure(create);const id=(await create.json()as{id?:string}).id;if(!id)return{status:"unknown"};children.push(id)}const createParent=await this.post(base,token,j.accountRef,"media",{media_type:"CAROUSEL",children:children.join(","),caption:j.content});if(!createParent.ok)return failure(createParent);parent=(await createParent.json()as{id?:string}).id;if(!parent)return{status:"unknown"};return this.publishContainer(base,token,j.accountRef,parent)}catch{return{status:"unknown",...(parent?{providerCorrelationId:parent}:{})}}}
private post(base:string,token:string,accountRef:string,path:string,body:unknown){return this.fetchImpl(`${base}/${accountRef}/${path}`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify(body)})}
private async publishContainer(base:string,token:string,accountRef:string,container:string):Promise<ProviderPublishResult>{const publish=await this.post(base,token,accountRef,"media_publish",{creation_id:container});if(!publish.ok)return failure(publish,container);const id=(await publish.json()as{id?:string}).id;return id?{status:"published",externalPostId:id,providerCorrelationId:container}:{status:"unknown",providerCorrelationId:container}}
}
function media(j:PublishingJob):PublishMediaItem[]{if(Array.isArray(j.mediaItems)&&j.mediaItems.length)return j.mediaItems;const kind=j.contentType==="image"||j.contentType==="carousel"?"image":"video";return(j.mediaUrls??[]).map(url=>({kind,url}))}
function failure(r:Response,correlation?:string):ProviderPublishResult{const retryable=r.status===429||r.status>=500;const retry=Number(r.headers.get("retry-after"));return{status:"failed",failureCode:`provider-http-${r.status}`,retryable,...(Number.isFinite(retry)&&retry>=0?{retryAfterSeconds:retry}:{}),...(correlation?{providerCorrelationId:correlation}:{})}}
function requiredVersion(v:string){if(!/^\d{6}$/.test(v))throw new Error("LinkedIn API version must use YYYYMM");return v}function requiredGraph(v:string){if(!/^v\d+\.\d+$/.test(v))throw new Error("Instagram Graph version is invalid");return v}function safeMedia(v:string|undefined){if(!v)return false;try{const u=new URL(v),h=u.hostname.toLowerCase();return u.protocol==="https:"&&!u.username&&!u.password&&!isPrivate(h)}catch{return false}}function isPrivate(h:string){return h==="localhost"||h.endsWith(".localhost")||h==="[::1]"||h==="0.0.0.0"||h.startsWith("[fc")||h.startsWith("[fd")||h.startsWith("[fe8")||/^127\./.test(h)||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||/^172\.(1[6-9]|2\d|3[01])\./.test(h)}
async function credential(resolver:PublishingSecretResolver,ref:string){try{const value=(await resolver.resolve(ref)).trim();return value||null}catch{return null}}
