"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {KairoIcon} from "./kairo-icons";
type BrandChoice={id:string;workspaceId:string;name:string};
export function BrandSwitcher({brands,currentBrandId,addBrandHref,compact=false}:{brands:BrandChoice[];currentBrandId?:string|null;addBrandHref:string;compact?:boolean}){const [pinned,setPinned]=useState<string[]>([]),[recent,setRecent]=useState<string[]>([]);useEffect(()=>{setPinned(read("kairo-pinned-brands"));setRecent(read("kairo-recent-brands"))},[]);const current=brands.find(b=>b.id===currentBrandId);const ordered=useMemo(()=>[...brands].sort((a,b)=>rank(b.id,pinned,recent)-rank(a.id,pinned,recent)),[brands,pinned,recent]);function visit(id:string){const next=[id,...recent.filter(x=>x!==id)].slice(0,5);setRecent(next);localStorage.setItem("kairo-recent-brands",JSON.stringify(next))}function pin(id:string){const next=pinned.includes(id)?pinned.filter(x=>x!==id):[...pinned,id];setPinned(next);localStorage.setItem("kairo-pinned-brands",JSON.stringify(next))}return <details className={`brand-switcher ${compact?"compact":""}`}><summary title="Switch Brand"><span className="brand-avatar" aria-hidden="true">{initials(current?.name??"Brand")}</span><span className="brand-switcher-copy"><small>Current Brand</small><strong>{current?.name??"Select Brand"}</strong></span><KairoIcon name="chevron"/></summary><div className="brand-switcher-menu"><p>Switch Brand</p>{ordered.map(brand=><div className="brand-switcher-row" key={brand.id}><Link href={`/?workspace=${encodeURIComponent(brand.workspaceId)}&brand=${encodeURIComponent(brand.id)}`} onClick={()=>visit(brand.id)} aria-current={brand.id===currentBrandId?"true":undefined}><span className="brand-avatar" aria-hidden="true">{initials(brand.name)}</span><span>{brand.name}</span>{brand.id===currentBrandId?<small>Current</small>:recent.includes(brand.id)?<small>Recent</small>:null}</Link><button type="button" onClick={()=>pin(brand.id)} aria-pressed={pinned.includes(brand.id)} title={pinned.includes(brand.id)?`Unpin ${brand.name}`:`Pin ${brand.name}`}><span aria-hidden="true">{pinned.includes(brand.id)?"★":"☆"}</span><span className="sr-only">{pinned.includes(brand.id)?"Unpin":"Pin"} {brand.name}</span></button></div>)}<Link href={addBrandHref}><KairoIcon name="plus"/><span>Add Brand</span></Link></div></details>}
function read(key:string){try{const value=JSON.parse(localStorage.getItem(key)??"[]");return Array.isArray(value)?value.filter(x=>typeof x==="string"):[]}catch{return[]}}
function rank(id:string,pinned:string[],recent:string[]){const pin=pinned.indexOf(id),recency=recent.indexOf(id);return(pin<0?0:100-pin)+(recency<0?0:20-recency)}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"B"}
