import { DomainValidationError } from "./index";
import type { ContentApproval } from "./review";

export type PublishChannel="linkedin"|"instagram"|"manual";
export type PublishCapability="publish-text"|"publish-image"|"publish-video"|"publish-carousel";
export type PublishContentType="text"|"image"|"video"|"carousel";
export type PublishStatus="scheduled"|"dispatching"|"published"|"failed"|"unknown"|"manual-required"|"cancelled";
export interface ChannelAccount{id:string;workspaceId:string;brandId:string;channel:PublishChannel;accountRef:string;displayName:string;credentialRef:string;capabilities:PublishCapability[];status:"connected"|"reconnect-required"|"disabled";connectedAt:string}
export interface PublishCommand{id:string;workspaceId:string;brandId:string;campaignId:string;assetId:string;versionId:string;version:number;approvalId:string;channelAccountId:string;channel:PublishChannel;accountRef:string;contentType:PublishContentType;scheduledFor:string;status:PublishStatus;attemptCount:number;createdAt:string;lastAttemptAt?:string}
export interface PublishAttempt{id:string;commandId:string;versionId:string;idempotencyKey:string;attemptNumber:number;status:"dispatching"|"published"|"failed"|"unknown";startedAt:string;completedAt?:string;externalPostId?:string;providerCorrelationId?:string;failureCode?:string}
export interface PublishedPost{id:string;workspaceId:string;brandId:string;campaignId:string;assetId:string;versionId:string;publishCommandId:string;channel:string;accountRef:string;externalPostId:string;publishedAt:string}

export function connectChannelAccount(input:Omit<ChannelAccount,"status">):ChannelAccount{return{id:text(input.id,"id",200),workspaceId:text(input.workspaceId,"workspaceId",200),brandId:text(input.brandId,"brandId",200),channel:one(input.channel,["linkedin","instagram","manual"],"channel"),accountRef:text(input.accountRef,"accountRef",300),displayName:text(input.displayName,"displayName",300),credentialRef:text(input.credentialRef,"credentialRef",500),capabilities:unique(input.capabilities),status:"connected",connectedAt:time(input.connectedAt,"connectedAt")}}
export function createPublishCommand(input:{id:string;approval:ContentApproval;currentVersionId:string;channelAccount:ChannelAccount;contentType:PublishContentType;scheduledFor:string;createdAt:string}):PublishCommand{const a=input.approval,c=input.channelAccount;if(text(input.currentVersionId,"currentVersionId",200)!==a.versionId)throw new DomainValidationError("Publishing requires the current approved version");if(a.workspaceId!==c.workspaceId||a.brandId!==c.brandId)throw new DomainValidationError("Channel Account is outside approval scope");if(a.destination.channel!==c.channel||a.destination.accountRef!==c.accountRef)throw new DomainValidationError("Approval destination does not match Channel Account");const contentType=one(input.contentType,["text","image","video","carousel"],"contentType"),cap=`publish-${contentType}` as PublishCapability,scheduledFor=time(input.scheduledFor,"scheduledFor"),createdAt=time(input.createdAt,"createdAt");if(Date.parse(scheduledFor)<Date.parse(createdAt))throw new DomainValidationError("scheduledFor cannot be in the past");const automatic=c.status==="connected"&&c.channel!=="manual"&&c.capabilities.includes(cap);return{id:text(input.id,"id",200),workspaceId:a.workspaceId,brandId:a.brandId,campaignId:a.campaignId,assetId:a.assetId,versionId:a.versionId,version:a.version,approvalId:a.id,channelAccountId:c.id,channel:c.channel,accountRef:c.accountRef,contentType,scheduledFor,status:automatic?"scheduled":"manual-required",attemptCount:0,createdAt}}
export function beginPublishAttempt(input:{id:string;command:PublishCommand;startedAt:string}):PublishAttempt{if(input.command.status!=="scheduled"&&input.command.status!=="failed")throw new DomainValidationError("Publish Command is not dispatchable");if(input.command.attemptCount>=3)throw new DomainValidationError("Publish retry limit reached");return{id:text(input.id,"id",200),commandId:input.command.id,versionId:input.command.versionId,idempotencyKey:`${input.command.id}:${input.command.versionId}:${input.command.accountRef}`,attemptNumber:input.command.attemptCount+1,status:"dispatching",startedAt:time(input.startedAt,"startedAt")}}
export function reconcilePublishAttempt(input:{attempt:PublishAttempt;outcome:"published"|"failed"|"unknown";checkedAt:string;externalPostId?:string;providerCorrelationId?:string;failureCode?:string}):PublishAttempt{if(input.attempt.status==="published")throw new DomainValidationError("Published attempt is terminal");const status=one(input.outcome,["published","failed","unknown"],"outcome");if(status==="published"&&!input.externalPostId)throw new DomainValidationError("Published outcome requires externalPostId");return{...input.attempt,status,completedAt:time(input.checkedAt,"checkedAt"),...(input.externalPostId?{externalPostId:text(input.externalPostId,"externalPostId",500)}:{}),...(input.providerCorrelationId?{providerCorrelationId:text(input.providerCorrelationId,"providerCorrelationId",500)}:{}),...(input.failureCode?{failureCode:text(input.failureCode,"failureCode",200)}:{})}}
export function applyPublishAttempt(command:PublishCommand,attempt:PublishAttempt):PublishCommand{if(attempt.commandId!==command.id||attempt.versionId!==command.versionId)throw new DomainValidationError("Publish Attempt does not match command");if(attempt.attemptNumber!==command.attemptCount+1&&attempt.attemptNumber!==command.attemptCount)throw new DomainValidationError("Publish Attempt sequence is invalid");return{...command,status:attempt.status,attemptCount:attempt.attemptNumber,lastAttemptAt:attempt.completedAt??attempt.startedAt}}
export function createPublishedPost(input:{id:string;command:PublishCommand;attempt:PublishAttempt}):PublishedPost{const {command,attempt}=input;if(command.status!=="published"||attempt.status!=="published"||attempt.commandId!==command.id||attempt.versionId!==command.versionId||!attempt.externalPostId||!attempt.completedAt)throw new DomainValidationError("Published Post requires a matching successful attempt");return{id:text(input.id,"id",200),workspaceId:command.workspaceId,brandId:command.brandId,campaignId:command.campaignId,assetId:command.assetId,versionId:command.versionId,publishCommandId:command.id,channel:command.channel,accountRef:command.accountRef,externalPostId:attempt.externalPostId,publishedAt:attempt.completedAt}}
export function retryPublishCommand(command:PublishCommand,at:string):PublishCommand{if(command.status!=="failed"&&command.status!=="unknown")throw new DomainValidationError("Only failed or unknown publishing can be retried");if(command.attemptCount>=3)throw new DomainValidationError("Publish retry limit reached");return{...command,status:"scheduled",lastAttemptAt:time(at,"lastAttemptAt")}}
function text(v:unknown,f:string,max:number){if(typeof v!=="string"||!v.trim())throw new DomainValidationError(`${f} is required`);const n=v.trim();if(n.length>max)throw new DomainValidationError(`${f} is too long`);return n}
function time(v:unknown,f:string){const n=text(v,f,80);if(Number.isNaN(Date.parse(n)))throw new DomainValidationError(`${f} must be a valid timestamp`);return n}
function one<const T extends string>(v:unknown,values:readonly T[],f:string):T{if(typeof v!=="string"||!values.includes(v as T))throw new DomainValidationError(`${f} is not supported`);return v as T}
function unique(v:unknown):PublishCapability[]{if(!Array.isArray(v))throw new DomainValidationError("capabilities must be a list");const values=v.map(x=>one(x,["publish-text","publish-image","publish-video","publish-carousel"],"capability"));if(new Set(values).size!==values.length)throw new DomainValidationError("capabilities must not contain duplicates");return values}
