import { describe, expect, it } from "vitest";
import { applyPublishAttempt, beginPublishAttempt, cancelPublishCommand, connectChannelAccount, createPublishedPost, createPublishCommand, reconcilePublishAttempt, retryPublishCommand } from "./publishing";
import type { ContentApproval } from "./review";

const approval:ContentApproval={id:"approval-1",reviewId:"review-1",approverAccountId:"human-1",workspaceId:"ws-1",brandId:"brand-1",campaignId:"campaign-1",assetId:"asset-1",versionId:"version-2",version:2,destination:{channel:"linkedin",accountRef:"page-1"},approvedAt:"2026-08-13T10:00:00Z"};

describe("VS-07 publishing domain",()=>{
  it("stores only an opaque credential reference and explicit capabilities",()=>{const account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-text"],connectedAt:"2026-08-13T10:01:00Z"});expect(account).toMatchObject({credentialRef:"vault://channels/1",status:"connected"});expect(account).not.toHaveProperty("accessToken")});
  it("schedules only the exact current approved version and destination",()=>{const account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-text"],connectedAt:"2026-08-13T10:01:00Z"});expect(()=>createPublishCommand({id:"publish-1",approval,currentVersionId:"version-3",channelAccount:account,contentType:"text",scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z"})).toThrow(/current approved version/i);expect(()=>createPublishCommand({id:"publish-1",approval:{...approval,destination:{channel:"linkedin",accountRef:"other"}},currentVersionId:"version-2",channelAccount:account,contentType:"text",scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z"})).toThrow(/destination/i)});
  it("degrades unsupported capability to manual-required",()=>{const account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-text"],connectedAt:"2026-08-13T10:01:00Z"});const command=createPublishCommand({id:"publish-1",approval,currentVersionId:"version-2",channelAccount:account,contentType:"video",scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z"});expect(command.status).toBe("manual-required")});
  it("uses stable idempotency and keeps timeouts unknown until reconciliation",()=>{const account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-text"],connectedAt:"2026-08-13T10:01:00Z"});const command=createPublishCommand({id:"publish-1",approval,currentVersionId:"version-2",channelAccount:account,contentType:"text",scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z"});const attempt=beginPublishAttempt({id:"attempt-1",command,startedAt:"2026-08-14T10:00:00Z"});expect(attempt.idempotencyKey).toBe("publish-1:version-2:page-1");const unknown=reconcilePublishAttempt({attempt,outcome:"unknown",checkedAt:"2026-08-14T10:01:00Z"});expect(unknown.status).toBe("unknown");expect(()=>retryPublishCommand({...command,status:"unknown",attemptCount:3},"2026-08-14T10:02:00Z")).toThrow(/retry limit/i)});
  it("records attempt sequence and creates immutable published identity",()=>{const account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-text"],connectedAt:"2026-08-13T10:01:00Z"});const command=createPublishCommand({id:"publish-1",approval,currentVersionId:"version-2",channelAccount:account,contentType:"text",scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z"});const attempt=reconcilePublishAttempt({attempt:beginPublishAttempt({id:"attempt-1",command,startedAt:"2026-08-14T10:00:00Z"}),outcome:"published",externalPostId:"urn:li:share:123",checkedAt:"2026-08-14T10:01:00Z"});const completed=applyPublishAttempt(command,attempt);expect(completed).toMatchObject({status:"published",attemptCount:1});expect(createPublishedPost({id:"post-1",command:completed,attempt})).toMatchObject({versionId:"version-2",externalPostId:"urn:li:share:123"})});
  it("cancels only commands that have not started dispatch",()=>{const pending={id:"p",workspaceId:"w",brandId:"b",campaignId:"c",assetId:"a",versionId:"v",version:1,approvalId:"q",channelAccountId:"ca",channel:"manual",accountRef:"manual",contentType:"text",scheduledFor:"2026-08-14T10:00:00Z",status:"manual-required",attemptCount:0,createdAt:"2026-08-13T10:00:00Z"}as const;expect(cancelPublishCommand(pending).status).toBe("cancelled");expect(()=>cancelPublishCommand({...pending,status:"published"})).toThrow(/pending/i)});
});
