"use server";
import{redirect}from"next/navigation";import{appendContentEdit,approveContentVersionRequest,createCampaign,createContentAsset,generateContentVersion,requestContentReview}from"../../../../src/lib/kairo-api";
const url=(b:string,c?:string)=>`/brands/${encodeURIComponent(b)}/campaigns${c?`/${encodeURIComponent(c)}`:""}`;
export async function createCampaignAction(brandId:string,form:FormData){try{const c=await createCampaign(brandId,{ideaId:String(form.get("ideaId")??""),name:String(form.get("name")??""),objective:String(form.get("objective")??"")});redirect(`${url(brandId,c.id)}?notice=${encodeURIComponent("Campaign created")}`)}catch(e){redirect(`${url(brandId)}?error=${encodeURIComponent(e instanceof Error?e.message:"Unable to create Campaign")}`)}}
export async function createAssetAction(brandId:string,campaignId:string,form:FormData){try{await createContentAsset(brandId,campaignId,{channel:String(form.get("channel")??"manual"),format:String(form.get("format")??"text"),audience:String(form.get("audience")??""),topic:String(form.get("topic")??""),hookType:String(form.get("hookType")??""),cta:String(form.get("cta")??""),content:String(form.get("content")??"")});redirect(`${url(brandId,campaignId)}?notice=${encodeURIComponent("Content Asset created")}`)}catch(e){redirect(`${url(brandId,campaignId)}?error=${encodeURIComponent(e instanceof Error?e.message:"Unable to create content")}`)}}
export async function saveVersionAction(brandId:string,campaignId:string,assetId:string,expectedVersion:number,form:FormData){try{await appendContentEdit(brandId,campaignId,assetId,{expectedVersion,content:String(form.get("content")??"")});redirect(`${url(brandId,campaignId)}?notice=${encodeURIComponent("New Content Version saved")}`)}catch(e){redirect(`${url(brandId,campaignId)}?error=${encodeURIComponent(e instanceof Error?e.message:"Unable to save version")}`)}}
export async function generateVersionAction(brandId:string,campaignId:string,assetId:string,expectedVersion:number,action:string){try{await generateContentVersion(brandId,campaignId,assetId,{expectedVersion,action,brandContextVersion:`${brandId}@current`});redirect(`${url(brandId,campaignId)}?notice=${encodeURIComponent("AI-assisted version created")}`)}catch(e){redirect(`${url(brandId,campaignId)}?error=${encodeURIComponent(e instanceof Error?e.message:"Unable to generate version")}`)}}
export async function reviewContentAction(brandId:string,campaignId:string,assetId:string,expectedVersion:number){try{await requestContentReview(brandId,campaignId,assetId,{expectedVersion,brandContextVersion:`${brandId}@current`,revisionCycle:0});redirect(`${url(brandId,campaignId)}?notice=${encodeURIComponent("Current version reviewed")}`)}catch(e){redirect(`${url(brandId,campaignId)}?error=${encodeURIComponent(e instanceof Error?e.message:"Unable to review version")}`)}}
export async function approveContentAction(brandId:string,campaignId:string,assetId:string,expectedVersion:number,channel:"linkedin"|"instagram"|"manual",form:FormData){try{await approveContentVersionRequest(brandId,campaignId,assetId,{expectedVersion,destination:{channel,accountRef:String(form.get("accountRef")??"")}});redirect(`${url(brandId,campaignId)}?notice=${encodeURIComponent(`Version ${expectedVersion} approved`)}`)}catch(e){redirect(`${url(brandId,campaignId)}?error=${encodeURIComponent(e instanceof Error?e.message:"Unable to approve version")}`)}}
