import { redirect } from "next/navigation";
import { getBrand,getSession } from "../../../../../src/lib/kairo-api";
import { getMetaCandidates } from "../../../../../src/lib/meta-connection-api";
import { safeBrandReturnTo } from "../../../../../src/lib/brand-source-navigation";
import { KairoProductShell } from "../../../../kairo-product-shell";
import { selectMetaConnectionAction } from "../actions";
import "../../../../guided-brain.css";
type Params=Promise<{brandId:string}>;type SearchParams=Promise<{intent?:string;returnTo?:string;error?:string}>;
export default async function SelectMetaConnectionPage({params,searchParams}:{params:Params;searchParams:SearchParams}){const session=await getSession();if(!session)redirect("/");const{brandId}=await params,query=await searchParams,brand=await getBrand(brandId);if(!brand)redirect("/");const workspace=session.workspaces.find(item=>item.id===brand.workspaceId);if(!workspace)redirect("/");const returnTo=safeBrandReturnTo(query.returnTo,brandId),result=await loadCandidates(brandId,query.intent);return <KairoProductShell brandId={brandId} workspaceId={workspace.id} active="Brand Brain" mobileActive="More"><main id="kairo-main-content" tabIndex={-1} className="workspace-main brand-brain-workspace"><header className="topbar brain-page-header"><div><p className="eyebrow">Account selection</p><h1>Choose what to connect</h1><p className="lede">Select the exact Page or Professional account Kairo may use for this Brand.</p></div></header>{query.error?<p className="notice error" role="alert">{query.error}</p>:null}{result.error?<p className="notice error" role="alert">{result.error}</p>:null}<section className="brain-source-panel brain-source-hub" aria-labelledby="candidate-heading"><div><p className="eyebrow">Available accounts</p><h2 id="candidate-heading">Eligible Meta destinations</h2><p>Nothing is connected until you choose. Permissions stay scoped to this Brand.</p></div>{result.candidates.length?<div className="meta-candidate-list">{result.candidates.map(candidate=><article className="meta-candidate-card" key={candidate.id}><div><span className="source-kind">{candidate.channel} · {candidate.authMethod}</span><strong>{candidate.username?`@${candidate.username}`:candidate.displayName}</strong><small>{candidate.pageName?`${candidate.pageName} · `:""}{candidate.channel} {candidate.accountRef}</small></div><form action={selectMetaConnectionAction.bind(null,brandId,query.intent!,candidate.id,returnTo)}><button className="primary-button" type="submit">Connect this account</button></form></article>)}</div>:!result.error?<div className="brain-ready-note"><div><strong>No eligible accounts found.</strong><span>Return to Brand Brain and try another connection method.</span></div></div>:null}<a className="tertiary-button" href={returnTo}>Skip this connection</a></section></main></KairoProductShell>}
async function loadCandidates(brandId:string,intent?:string){if(!intent)return{candidates:[],error:"Connection selection expired or is incomplete."};try{return{candidates:await getMetaCandidates(brandId,intent),error:""}}catch(error){return{candidates:[],error:error instanceof Error?error.message:"Unable to load eligible accounts"}}}
