import type { Pool,PoolClient } from "pg";
import { ConcurrencyConflictError,ResourceNotFoundError } from "@kairo/domain";
import type { ChannelAccount,PublishAttempt,PublishCommand,PublishedPost } from "@kairo/domain/publishing";
import type { PublishingRepository } from "@kairo/domain/publishing-service";

export class PgPublishingRepository implements PublishingRepository{
 constructor(private pool:Pool){}
 async saveChannelAccount(a:string,c:ChannelAccount){const x=await this.pool.connect();try{const ws=await scope(x,a,c.brandId);if(ws!==c.workspaceId)throw new ResourceNotFoundError("Brand not found");await x.query(`insert into channel_accounts(id,workspace_id,brand_id,channel,account_ref,display_name,credential_ref,capabilities,status,connected_at) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10) on conflict(brand_id,channel,account_ref) do update set display_name=excluded.display_name,credential_ref=excluded.credential_ref,capabilities=excluded.capabilities,status=excluded.status,connected_at=excluded.connected_at`,[c.id,c.workspaceId,c.brandId,c.channel,c.accountRef,c.displayName,c.credentialRef,JSON.stringify(c.capabilities),c.status,c.connectedAt]);const found=await this.byAccount(x,ws,c.brandId,c.channel,c.accountRef);return found!}finally{x.release()}}
 async getChannelAccount(a:string,b:string,id:string){const x=await this.pool.connect();try{const ws=await scope(x,a,b);const q=await x.query(`select * from channel_accounts where workspace_id=$1 and brand_id=$2 and id=$3`,[ws,b,id]);return q.rows[0]?channel(q.rows[0]):null}finally{x.release()}}
 async listChannelAccounts(a:string,b:string){const x=await this.pool.connect();try{const ws=await scope(x,a,b);const q=await x.query(`select * from channel_accounts where workspace_id=$1 and brand_id=$2 order by connected_at desc,id`,[ws,b]);return q.rows.map(channel)}finally{x.release()}}
 async saveCommand(a:string,c:PublishCommand){const x=await this.pool.connect();try{await scope(x,a,c.brandId);const q=await x.query(`insert into publish_commands(id,workspace_id,brand_id,campaign_id,asset_id,version_id,version,approval_id,channel_account_id,channel,account_ref,content_type,scheduled_for,status,attempt_count,created_at,last_attempt_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) on conflict(id) do update set status=excluded.status,last_attempt_at=excluded.last_attempt_at where publish_commands.status in ('failed','unknown') and excluded.status='scheduled' and publish_commands.attempt_count=excluded.attempt_count returning *`,params(c));if(!q.rows[0])throw new ConcurrencyConflictError("Publish Command changed");return command(q.rows[0])}finally{x.release()}}
 async getCommand(a:string,b:string,id:string){const x=await this.pool.connect();try{const ws=await scope(x,a,b);const q=await x.query(`select * from publish_commands where workspace_id=$1 and brand_id=$2 and id=$3`,[ws,b,id]);return q.rows[0]?command(q.rows[0]):null}finally{x.release()}}
 async listCommands(a:string,b:string,from?:string,to?:string){const x=await this.pool.connect();try{const ws=await scope(x,a,b);const q=await x.query(`select * from publish_commands where workspace_id=$1 and brand_id=$2 and ($3::timestamptz is null or scheduled_for >= $3) and ($4::timestamptz is null or scheduled_for <= $4) order by scheduled_for,id`,[ws,b,from??null,to??null]);return q.rows.map(command)}finally{x.release()}}
 async recordDispatch(a:string,c:PublishCommand,t:PublishAttempt){const x=await this.pool.connect();try{await x.query("begin");await scope(x,a,c.brandId);const q=await x.query(`update publish_commands set status='dispatching',attempt_count=$2,last_attempt_at=$3 where id=$1 and version_id=$4 and attempt_count=$2-1 and status in ('scheduled','failed') returning id`,[c.id,c.attemptCount,c.lastAttemptAt,c.versionId]);if(!q.rows[0])throw new ConcurrencyConflictError("Publish Command is no longer dispatchable");await insertAttempt(x,t);await x.query("commit");return t}catch(e){await rollback(x);throw e}finally{x.release()}}
 async getLatestAttempt(a:string,b:string,id:string){const x=await this.pool.connect();try{const ws=await scope(x,a,b);const q=await x.query(`select t.* from publish_attempts t join publish_commands c on c.id=t.command_id where c.workspace_id=$1 and c.brand_id=$2 and c.id=$3 order by t.attempt_number desc limit 1`,[ws,b,id]);return q.rows[0]?attempt(q.rows[0]):null}finally{x.release()}}
 async recordOutcome(a:string,c:PublishCommand,t:PublishAttempt,p?:PublishedPost){const x=await this.pool.connect();try{await x.query("begin");await scope(x,a,c.brandId);const q=await x.query(`update publish_commands set status=$2,last_attempt_at=$3 where id=$1 and version_id=$4 and status='dispatching' and attempt_count=$5 returning *`,[c.id,c.status,c.lastAttemptAt,c.versionId,c.attemptCount]);if(!q.rows[0])throw new ConcurrencyConflictError("Publish Attempt changed");const aq=await x.query(`update publish_attempts set status=$2,completed_at=$3,external_post_id=$4,provider_correlation_id=$5,failure_code=$6 where id=$1 and command_id=$7 and status='dispatching' returning id`,[t.id,t.status,t.completedAt??null,t.externalPostId??null,t.providerCorrelationId??null,t.failureCode??null,c.id]);if(!aq.rows[0])throw new ConcurrencyConflictError("Publish Attempt changed");if(p)await x.query(`insert into published_posts(id,workspace_id,brand_id,campaign_id,asset_id,version_id,publish_command_id,channel,account_ref,external_post_id,published_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[p.id,p.workspaceId,p.brandId,p.campaignId,p.assetId,p.versionId,p.publishCommandId,p.channel,p.accountRef,p.externalPostId,p.publishedAt]);await x.query("commit");return command(q.rows[0])}catch(e){await rollback(x);throw e}finally{x.release()}}
 private async byAccount(x:PoolClient,ws:string,b:string,ch:string,ref:string){const q=await x.query(`select * from channel_accounts where workspace_id=$1 and brand_id=$2 and channel=$3 and account_ref=$4`,[ws,b,ch,ref]);return q.rows[0]?channel(q.rows[0]):null}
}
function params(c:PublishCommand){return[c.id,c.workspaceId,c.brandId,c.campaignId,c.assetId,c.versionId,c.version,c.approvalId,c.channelAccountId,c.channel,c.accountRef,c.contentType,c.scheduledFor,c.status,c.attemptCount,c.createdAt,c.lastAttemptAt??null]}
async function insertAttempt(x:PoolClient,t:PublishAttempt){await x.query(`insert into publish_attempts(id,command_id,version_id,idempotency_key,attempt_number,status,started_at) values($1,$2,$3,$4,$5,$6,$7)`,[t.id,t.commandId,t.versionId,t.idempotencyKey,t.attemptNumber,t.status,t.startedAt])}
function channel(r:any):ChannelAccount{return{id:r.id,workspaceId:r.workspace_id,brandId:r.brand_id,channel:r.channel,accountRef:r.account_ref,displayName:r.display_name,credentialRef:r.credential_ref,capabilities:r.capabilities,status:r.status,connectedAt:iso(r.connected_at)}}
function command(r:any):PublishCommand{return{id:r.id,workspaceId:r.workspace_id,brandId:r.brand_id,campaignId:r.campaign_id,assetId:r.asset_id,versionId:r.version_id,version:r.version,approvalId:r.approval_id,channelAccountId:r.channel_account_id,channel:r.channel,accountRef:r.account_ref,contentType:r.content_type,scheduledFor:iso(r.scheduled_for),status:r.status,attemptCount:r.attempt_count,createdAt:iso(r.created_at),...(r.last_attempt_at?{lastAttemptAt:iso(r.last_attempt_at)}:{})}}
function attempt(r:any):PublishAttempt{return{id:r.id,commandId:r.command_id,versionId:r.version_id,idempotencyKey:r.idempotency_key,attemptNumber:r.attempt_number,status:r.status,startedAt:iso(r.started_at),...(r.completed_at?{completedAt:iso(r.completed_at)}:{}),...(r.external_post_id?{externalPostId:r.external_post_id}:{}),...(r.provider_correlation_id?{providerCorrelationId:r.provider_correlation_id}:{}),...(r.failure_code?{failureCode:r.failure_code}:{})}}
async function scope(x:PoolClient,a:string,b:string){const q=await x.query(`select b.workspace_id from brands b join workspace_memberships m on m.workspace_id=b.workspace_id where m.account_id=$1 and m.active=true and b.id=$2`,[a,b]);if(!q.rows[0])throw new ResourceNotFoundError("Brand not found");return q.rows[0].workspace_id as string}function iso(v:Date|string){return v instanceof Date?v.toISOString():new Date(v).toISOString()}async function rollback(x:PoolClient){try{await x.query("rollback")}catch{}}
