import type {Pool} from "pg";
import type {SimpleCreationRequest,SimpleCreationStatus,SimpleCreationStore} from "./simple-creation";
export class PgSimpleCreationStore implements SimpleCreationStore{
 constructor(private pool:Pool){}
 async create(v:SimpleCreationRequest){await this.pool.query(`insert into simple_creation_requests(id,account_id,workspace_id,brand_id,goal,input_text,source,content_preference,status,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10)`,[v.id,v.accountId,v.workspaceId,v.brandId,v.goal,v.input??null,v.source??null,v.contentPreference,v.status,v.createdAt]);return v;}
 async get(accountId:string,brandId:string,id:string){const r=await this.pool.query(`${select} where r.account_id=$1 and r.brand_id=$2 and r.id=$3`,[accountId,brandId,id]);return r.rows[0]?map(r.rows[0]):null;}
 async claim(workerId:string,leaseSeconds:number){const c=await this.pool.connect();try{await c.query("begin");const r=await c.query(`${select} where r.status not in ('ready','needs-attention') and (r.lease_expires_at is null or r.lease_expires_at<now()) order by r.created_at for update skip locked limit 1`);if(!r.rows[0]){await c.query("commit");return null;}await c.query(`update simple_creation_requests set lease_owner=$2,lease_expires_at=now()+($3*interval '1 second'),attempt=attempt+1,updated_at=now() where id=$1`,[r.rows[0].id,workerId,leaseSeconds]);await c.query("commit");return map({...r.rows[0],lease_owner:workerId,attempt:Number(r.rows[0].attempt)+1});}catch(e){await c.query("rollback");throw e;}finally{c.release();}}
 async advance(id:string,workerId:string,status:SimpleCreationStatus,p:Partial<SimpleCreationRequest>={}){const r=await this.pool.query(`update simple_creation_requests set status=$3,idea_id=coalesce($4,idea_id),recommended_angle_id=coalesce($5,recommended_angle_id),campaign_id=coalesce($6,campaign_id),recommendation=coalesce($7::jsonb,recommendation),failure_reason=coalesce($8,failure_reason),lease_owner=case when $3 in ('ready','needs-attention') then null else lease_owner end,lease_expires_at=case when $3 in ('ready','needs-attention') then null else lease_expires_at end,updated_at=now() where id=$1 and lease_owner=$2`,[id,workerId,status,p.ideaId??null,p.recommendedAngleId??null,p.campaignId??null,p.recommendation?JSON.stringify(p.recommendation):null,p.failureReason??null]);if(!r.rowCount)throw new Error("Creation lease was lost");}
}
const select=`select r.* from simple_creation_requests r`;
function map(r:any):SimpleCreationRequest{return{id:String(r.id),accountId:String(r.account_id),workspaceId:String(r.workspace_id),brandId:String(r.brand_id),goal:String(r.goal),...(r.input_text?{input:String(r.input_text)}:{}),...(r.source?{source:String(r.source)}:{}),contentPreference:r.content_preference,status:r.status,...(r.idea_id?{ideaId:String(r.idea_id)}:{}),...(r.recommended_angle_id?{recommendedAngleId:String(r.recommended_angle_id)}:{}),...(r.campaign_id?{campaignId:String(r.campaign_id)}:{}),...(r.recommendation?{recommendation:r.recommendation}:{}),...(r.failure_reason?{failureReason:String(r.failure_reason)}:{}),attempt:Number(r.attempt),createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()};}
