import Link from "next/link";
import { getBrand, getCampaignDetail, getChannelAccounts, getContentReviewStatus } from "../../../../../src/lib/kairo-api";
import { KairoSidebar } from "../../ideas/page";
import { approveContentAction, createAssetAction, generateVersionAction, reviewContentAction, saveVersionAction, scheduleContentAction } from "../actions";
import { ScheduleForm } from "./schedule-form";
type Params = Promise<{ brandId: string; campaignId: string }>;
type SearchParams = Promise<{ notice?: string; error?: string }>;
export default async function Studio({ params, searchParams }: { params: Params; searchParams: SearchParams }) {
  const { brandId, campaignId } = await params;
  const [brand, detail, channelAccounts, messages] = await Promise.all([getBrand(brandId), getCampaignDetail(brandId, campaignId), getChannelAccounts(brandId), searchParams]);
  if (!brand) return null;
  const reviewStatuses = new Map(await Promise.all(detail.assets.map(async ({ asset }) => [asset.id, await getContentReviewStatus(brand.id, asset.id)] as const)));
  return <div className="app-shell"><KairoSidebar brandId={brand.id} active="Content Studio" /><main className="workspace-main studio-main">
    <Link className="back-link" href={`/brands/${encodeURIComponent(brand.id)}/campaigns`}>← Campaigns</Link>
    <header className="studio-header"><div><p className="eyebrow">Content Studio</p><h1>{detail.campaign.name}</h1><p>{detail.campaign.objective}</p></div><span className="idea-status">Human controlled</span></header>
    {messages.notice ? <p className="notice success" role="status">{messages.notice}</p> : null}{messages.error ? <p className="notice error" role="alert">{messages.error}</p> : null}
    {detail.assets.length ? <div className="studio-assets">{detail.assets.map(({ asset, versions }) => {
      const current = versions.at(-1)!; const status = reviewStatuses.get(asset.id)!;
      const review = status.review?.versionId === current.id ? status.review : null; const approval = status.approval?.versionId === current.id ? status.approval : null;
      const label = approval ? "Approved" : review?.status === "passed" ? "Ready for approval" : review?.status === "revision-required" ? "Revision required" : "Draft";
      return <section className="studio-workspace" key={asset.id}>
        <div className="studio-toolbar"><div><span className="angle-channel">{asset.channel} · {asset.format}</span><h2>{asset.topic}</h2></div><div className="ai-actions" aria-label="Contextual AI actions">{[["simplify", "Simplify"], ["strengthen-opening", "Strengthen opening"], ["alternative", "Alternative"]].map(([action, actionLabel]) => <form action={generateVersionAction.bind(null, brand.id, campaignId, asset.id, asset.currentVersion, action!)} key={action}><button>{actionLabel}</button></form>)}</div></div>
        <div className="studio-columns"><form action={saveVersionAction.bind(null, brand.id, campaignId, asset.id, asset.currentVersion)} className="editor-panel"><label htmlFor={`content-${asset.id}`}>Content</label><textarea id={`content-${asset.id}`} name="content" defaultValue={current.content} required maxLength={50000} /><div className="editor-footer"><span>Version {current.version} · {current.actor}</span><button className="primary-button">Save new version</button></div></form><aside className="version-panel"><h3>Version history</h3>{[...versions].reverse().map((version) => <details key={version.id} open={version.id === current.id}><summary>Version {version.version} · {version.action}</summary><p>{version.content}</p><small>{new Date(version.createdAt).toLocaleString()}</small></details>)}<div className="evidence-access"><strong>Evidence lineage</strong><p>{detail.campaign.supportingClaimIds.length} supporting Claims retained.</p><Link href={`/brands/${encodeURIComponent(brand.id)}/ideas/${encodeURIComponent(detail.campaign.ideaId)}`}>Inspect Research</Link></div></aside></div>
        <section className="review-panel" aria-labelledby={`review-${asset.id}`}><div className="review-heading"><div><p className="eyebrow">Truth Gate + Critic</p><h3 id={`review-${asset.id}`}>Review version {current.version}</h3></div><span className={`review-status ${approval ? "approved" : review?.status ?? "draft"}`}>{label}</span></div>
          {review ? <div className="review-grid"><div><strong>Truth Gate</strong><p className={review.truth.passed ? "review-pass" : "review-fail"}>{review.truth.passed ? "Passed — evidence requirements satisfied." : "Hard failure — approval is blocked."}</p>{review.truth.findings.length ? <ul className="finding-list">{review.truth.findings.map((finding, index) => <li key={`${finding.code}-${index}`}><strong>{finding.code.replaceAll("-", " ")}</strong><span>{finding.message}</span></li>)}</ul> : null}</div><div><strong>Critic</strong>{review.critic ? <><p>{review.critic.score}/100 · {review.critic.passed ? "Passed" : "Revision required"}</p>{review.critic.findings.length ? <ul className="finding-list">{review.critic.findings.map((finding, index) => <li key={`${finding.code}-${index}`}><strong>{finding.severity}</strong><span>{finding.message}</span></li>)}</ul> : null}</> : <p>Not run because the Truth Gate failed.</p>}</div></div> : <p className="review-intro">Run deterministic evidence checks first, then the isolated Critic. Neither can approve or publish content.</p>}
          {!review || review.status === "revision-required" ? <form action={reviewContentAction.bind(null, brand.id, campaignId, asset.id, current.version)}><button className="secondary-button">{review ? "Review revised version" : "Review current version"}</button></form> : null}
          {review?.status === "passed" && !approval ? <form className="approval-form" action={approveContentAction.bind(null, brand.id, campaignId, asset.id, current.version, asset.channel)}><label>Destination account reference<input name="accountRef" required maxLength={300} placeholder="e.g. company-linkedin" /></label><button className="primary-button">Approve version {current.version}</button><p>Approval is destination-specific. It does not publish or schedule.</p></form> : null}
          {approval ? <><div className="approval-record"><strong>Human approval recorded</strong><p>{approval.destination.channel} · {approval.destination.accountRef} · {new Date(approval.approvedAt).toLocaleString()}</p><small>Editing creates a new immutable version that requires a new review and approval.</small></div>{(()=>{const account=channelAccounts.find(a=>a.channel===approval.destination.channel&&a.accountRef===approval.destination.accountRef&&a.status==="connected");return account&&account.capabilities.length?<ScheduleForm account={account} action={scheduleContentAction.bind(null,brand.id,campaignId,asset.id)}/>:<div className="schedule-unavailable"><strong>Manual publishing required</strong><p>No connected destination with matching capabilities is available for this approval. Kairo will not silently publish elsewhere.</p></div>})()}</> : null}
        </section>
      </section>;
    })}</div> : <section className="studio-empty"><div><p className="eyebrow">First Content Asset</p><h2>Create the writing surface</h2><p>Start manually; contextual AI actions remain secondary and every save creates a version.</p></div><form className="asset-form" action={createAssetAction.bind(null, brand.id, campaignId)}><label>Channel<select name="channel"><option value="linkedin">LinkedIn</option><option value="instagram">Instagram</option><option value="manual">Manual</option></select></label><label>Format<input name="format" defaultValue="text" required /></label><label>Audience<input name="audience" required /></label><label>Topic<input name="topic" required /></label><label>Hook type<input name="hookType" required /></label><label>CTA<input name="cta" required /></label><label className="wide">Initial content<textarea name="content" rows={10} required maxLength={50000} /></label><button className="primary-button wide">Create Content Asset</button></form></section>}
  </main></div>;
}
